"""add comment

Revision ID: 64154beaa039
Revises: 69de20270362
Create Date: 2022-06-04 22:31:17.999005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64154beaa039'
down_revision = '69de20270362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('recommended', sa.Integer(), nullable=True))
    op.add_column('book', sa.Column('comment', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'comment')
    op.drop_column('book', 'recommended')
    # ### end Alembic commands ###
